<?php

return [
    'farmer' => [
        'items' => [
            [
                'label' => 'My Active Harvests',
                'route' => 'harvests.*',
                'route_url' => 'harvests.index',
                'letter' => 'M',
                'tooltip' => 'My Active Harvests',
            ],
            [
                'label' => 'Selling',
                'route' => 'farmer.negotiations|farmer.proposals|farmer.haul-requests|pooling.cost-ledger*',
                'letter' => 'S',
                'tooltip' => 'Selling',
                'children' => [
                    [
                        'label' => 'My Negotiations',
                        'route' => 'farmer.negotiations',
                        'route_url' => 'farmer.negotiations',
                        'letter' => 'N',
                        'tooltip' => 'My Negotiations',
                    ],
                    [
                        'label' => 'Route Offers',
                        'route' => 'farmer.proposals',
                        'route_url' => 'farmer.proposals',
                        'letter' => 'R',
                        'tooltip' => 'Route Offers',
                    ],
                    [
                        'label' => 'Cost Ledger',
                        'route' => 'pooling.cost-ledger*',
                        'route_url' => 'pooling.cost-ledger.farmer-index',
                        'letter' => 'C',
                        'tooltip' => 'Cost Ledger',
                    ],
                    [
                        'label' => 'Haul Requests',
                        'route' => 'farmer.haul-requests',
                        'route_url' => 'farmer.haul-requests',
                        'letter' => 'H',
                        'tooltip' => 'Haul Requests',
                        'condition' => 'farmer_non_cooperative',
                    ],
                ],
            ],
            [
                'label' => 'Shipments',
                'route' => 'farmer.logistics|tracking.index',
                'letter' => 'T',
                'tooltip' => 'Shipments',
                'children' => [
                    [
                        'label' => 'My Logistics',
                        'route' => 'farmer.logistics',
                        'route_url' => 'farmer.logistics',
                        'letter' => 'L',
                        'tooltip' => 'My Logistics',
                    ],
                    [
                        'label' => 'Track Shipments',
                        'route' => 'tracking.index',
                        'route_url' => 'tracking.index',
                        'letter' => 'T',
                        'tooltip' => 'Track Shipments',
                    ],
                ],
            ],
            [
                'label' => 'Reports',
                'route' => 'farmer.reports.*',
                'route_url' => 'farmer.reports.sales',
                'letter' => 'R',
                'tooltip' => 'Reports',
            ],
            [
                'label' => 'Reference',
                'route' => 'prices.full|farmer.documents*',
                'letter' => 'B',
                'tooltip' => 'Reference',
                'children' => [
                    [
                        'label' => 'Market Prices',
                        'route' => 'prices.full',
                        'route_url' => 'prices.full',
                        'letter' => 'M',
                        'tooltip' => 'Market Prices',
                    ],
                    [
                        'label' => 'Regulatory Documents',
                        'route' => 'farmer.documents*',
                        'route_url' => 'farmer.documents',
                        'letter' => 'D',
                        'tooltip' => 'Regulatory Documents',
                    ],
                ],
            ],
            [
                'label' => 'My Profile',
                'route' => 'profile.*',
                'route_url' => 'profile.show',
                'letter' => 'M',
                'tooltip' => 'My Profile',
                'mobile_only' => true,
            ],
        ],
    ],

    'buyer' => [
        'section_label' => 'Market',
        'items' => [
            [
                'label' => 'Crop Board',
                'route' => 'buyer.crop-board',
                'route_url' => 'buyer.crop-board',
                'letter' => 'C',
                'tooltip' => 'Crop Board',
                'active_style' => 'buyer',
            ],
            [
                'label' => 'Delivery Tracking',
                'route' => 'buyer.tracking',
                'route_url' => 'buyer.tracking',
                'letter' => 'D',
                'tooltip' => 'Delivery Tracking',
                'active_style' => 'buyer',
            ],
            [
                'label' => 'Negotiations',
                'route' => 'buyer.negotiations',
                'route_url' => 'buyer.negotiations',
                'letter' => 'N',
                'tooltip' => 'Negotiations',
                'active_style' => 'buyer',
            ],
            [
                'label' => 'Market Prices',
                'route' => 'prices.full',
                'route_url' => 'prices.full',
                'letter' => 'M',
                'tooltip' => 'Market Prices',
                'active_style' => 'buyer',
            ],
            [
                'label' => 'My Profile',
                'route' => 'profile.*',
                'route_url' => 'profile.show',
                'letter' => 'M',
                'tooltip' => 'My Profile',
                'mobile_only' => true,
            ],
        ],
    ],

    'admin' => [
        'items' => [
            [
                'label' => 'Trust & Verification',
                'route' => 'admin.users*|admin.farmers*|admin.farmer-documents*|admin.logistics|admin.logistics.*|admin.logistics-documents*|admin.buyers*|admin.drivers*',
                'letter' => 'T',
                'tooltip' => 'Trust & Verification',
                'children' => [
                    [
                        'label' => 'User Management',
                        'route' => 'admin.users*',
                        'route_url' => 'admin.users',
                        'letter' => 'U',
                        'tooltip' => 'User Management',
                    ],
                    [
                        'label' => 'Farmer Verification',
                        'route' => 'admin.farmers*|admin.farmer-documents*',
                        'route_url' => 'admin.farmers',
                        'letter' => 'F',
                        'tooltip' => 'Farmer Verification',
                    ],
                    [
                        'label' => 'Buyer Verification',
                        'route' => 'admin.buyers*',
                        'route_url' => 'admin.buyers',
                        'letter' => 'B',
                        'tooltip' => 'Buyer Verification',
                    ],
                    [
                        'label' => 'Logistics Partners',
                        'route' => 'admin.logistics|admin.logistics.*|admin.logistics-documents*',
                        'route_url' => 'admin.logistics',
                        'letter' => 'L',
                        'tooltip' => 'Logistics Partners',
                    ],
                    [
                        'label' => 'Driver Verification',
                        'route' => 'admin.drivers*',
                        'route_url' => 'admin.drivers',
                        'letter' => 'D',
                        'tooltip' => 'Driver Verification',
                    ],
                ],
            ],
            [
                'label' => 'Crops & Harvests',
                'route' => 'admin.harvests*|admin.crops*',
                'letter' => 'C',
                'tooltip' => 'Crops & Harvests',
                'children' => [
                    [
                        'label' => 'Harvest Oversight',
                        'route' => 'admin.harvests*',
                        'route_url' => 'admin.harvests',
                        'letter' => 'H',
                        'tooltip' => 'Harvest Oversight',
                    ],
                    [
                        'label' => 'Crop Registry',
                        'route' => 'admin.crops*',
                        'route_url' => 'admin.crops.index',
                        'letter' => 'C',
                        'tooltip' => 'Crop Registry',
                    ],
                ],
            ],
            [
                'label' => 'Governance',
                'route' => 'admin.audit-logs*|admin.analytics*',
                'letter' => 'G',
                'tooltip' => 'Governance',
                'children' => [
                    [
                        'label' => 'Platform Analytics',
                        'route' => 'admin.analytics*',
                        'route_url' => 'admin.analytics',
                        'letter' => 'A',
                        'tooltip' => 'Platform Analytics',
                    ],
                    [
                        'label' => 'Platform Audit Logs',
                        'route' => 'admin.audit-logs*',
                        'route_url' => 'admin.audit-logs',
                        'letter' => 'L',
                        'tooltip' => 'Platform Audit Logs',
                    ],
                ],
            ],
        ],
    ],

    'logistics_partner' => [
        // Cooperative logistics: Dashboard, Crop Board, Operations, Proposal Inbox,
        // Deliveries, Route Pricing, Transport (user-specified order).
        'items' => [
            [
                'label' => 'Crop Board',
                'route' => 'buyer.crop-board',
                'route_url' => 'buyer.crop-board',
                'letter' => 'C',
                'tooltip' => 'Crop Board',
                'condition' => 'cooperative_only',
            ],
            [
                'label' => 'Operations',
                'route' => 'route.optimization|pooling.cost-ledger*',
                'letter' => 'O',
                'tooltip' => 'Operations',
                'children' => [
                    [
                        'label' => 'Route Planning',
                        'route' => 'route.optimization',
                        'route_url' => 'route.optimization',
                        'letter' => 'R',
                        'tooltip' => 'Route Planning',
                    ],
                    [
                        'label' => 'Cost Ledger',
                        'route' => 'pooling.cost-ledger*',
                        'route_url' => 'pooling.cost-ledger.index',
                        'letter' => 'C',
                        'tooltip' => 'Cost Ledger',
                    ],
                ],
            ],
            [
                'label' => 'Proposal Inbox',
                'route' => 'pooling.index',
                'route_url' => 'pooling.index',
                'letter' => 'P',
                'tooltip' => 'Proposal Inbox',
            ],
            [
                'label' => 'Deliveries',
                'route' => 'buyer.tracking',
                'route_url' => 'buyer.tracking',
                'letter' => 'D',
                'tooltip' => 'Deliveries',
                'condition' => 'cooperative_only',
            ],
            [
                'label' => 'Members',
                'route' => 'logistics.members*',
                'route_url' => 'logistics.members.index',
                'letter' => 'M',
                'tooltip' => 'Members',
                'condition' => 'cooperative_only',
            ],
            [
                'label' => 'Route Pricing',
                'route' => 'profile.route-pricing',
                'route_url' => 'profile.route-pricing',
                'letter' => 'R',
                'tooltip' => 'Route Pricing',
            ],
            [
                'label' => 'Transport',
                'route' => 'logistics.drivers*|logistics.vehicles*|logistics.reports.*|logistics.analytics|logistics.capacity',
                'letter' => 'T',
                'tooltip' => 'Transport',
                'children' => [
                    [
                        'label' => 'Drivers',
                        'route' => 'logistics.drivers*',
                        'route_url' => 'logistics.drivers.index',
                        'letter' => 'D',
                        'tooltip' => 'Drivers',
                    ],
                    [
                        'label' => 'Vehicles',
                        'route' => 'logistics.vehicles*',
                        'route_url' => 'logistics.vehicles.index',
                        'letter' => 'V',
                        'tooltip' => 'Vehicles',
                    ],
                    [
                        'label' => 'Trip Reports',
                        'route' => 'logistics.reports.*|logistics.analytics',
                        'route_url' => 'logistics.reports.trips',
                        'letter' => 'R',
                        'tooltip' => 'Trip Reports',
                    ],
                    [
                        'label' => 'Capacity',
                        'route' => 'logistics.capacity',
                        'route_url' => 'logistics.capacity',
                        'letter' => 'C',
                        'tooltip' => 'Capacity',
                    ],
                ],
            ],
            [
                'label' => 'My Profile',
                'route' => 'profile.*',
                'route_url' => 'profile.show',
                'letter' => 'M',
                'tooltip' => 'My Profile',
                'mobile_only' => true,
            ],
        ],
        // Independent logistics: keeps its original order minus Reference.
        'items_independent' => [
            [
                'label' => 'Proposal Inbox',
                'route' => 'pooling.index',
                'route_url' => 'pooling.index',
                'letter' => 'P',
                'tooltip' => 'Proposal Inbox',
            ],
            [
                'label' => 'Operations',
                'route' => 'route.optimization|pooling.cost-ledger*',
                'letter' => 'O',
                'tooltip' => 'Operations',
                'children' => [
                    [
                        'label' => 'Route Planning',
                        'route' => 'route.optimization',
                        'route_url' => 'route.optimization',
                        'letter' => 'R',
                        'tooltip' => 'Route Planning',
                    ],
                    [
                        'label' => 'Cost Ledger',
                        'route' => 'pooling.cost-ledger*',
                        'route_url' => 'pooling.cost-ledger.index',
                        'letter' => 'C',
                        'tooltip' => 'Cost Ledger',
                    ],
                ],
            ],
            [
                'label' => 'Transport',
                'route' => 'logistics.drivers*|logistics.vehicles*|logistics.reports.*|logistics.analytics|logistics.capacity',
                'letter' => 'T',
                'tooltip' => 'Transport',
                'children' => [
                    [
                        'label' => 'Drivers',
                        'route' => 'logistics.drivers*',
                        'route_url' => 'logistics.drivers.index',
                        'letter' => 'D',
                        'tooltip' => 'Drivers',
                    ],
                    [
                        'label' => 'Vehicles',
                        'route' => 'logistics.vehicles*',
                        'route_url' => 'logistics.vehicles.index',
                        'letter' => 'V',
                        'tooltip' => 'Vehicles',
                    ],
                    [
                        'label' => 'Trip Reports',
                        'route' => 'logistics.reports.*|logistics.analytics',
                        'route_url' => 'logistics.reports.trips',
                        'letter' => 'R',
                        'tooltip' => 'Trip Reports',
                    ],
                    [
                        'label' => 'Capacity',
                        'route' => 'logistics.capacity',
                        'route_url' => 'logistics.capacity',
                        'letter' => 'C',
                        'tooltip' => 'Capacity',
                    ],
                ],
            ],
            [
                'label' => 'Route Pricing',
                'route' => 'profile.route-pricing',
                'route_url' => 'profile.route-pricing',
                'letter' => 'R',
                'tooltip' => 'Route Pricing',
            ],
            [
                'label' => 'Live Tracking',
                'route' => 'tracking.index',
                'route_url' => 'tracking.index',
                'letter' => 'T',
                'tooltip' => 'Live Tracking',
            ],
            [
                'label' => 'Haul Negotiations',
                'route' => 'logistics.haul-negotiations',
                'route_url' => 'logistics.haul-negotiations',
                'letter' => 'H',
                'tooltip' => 'Haul Negotiations',
            ],
            [
                'label' => 'My Profile',
                'route' => 'profile.*',
                'route_url' => 'profile.show',
                'letter' => 'M',
                'tooltip' => 'My Profile',
                'mobile_only' => true,
            ],
        ],
    ],

    'driver' => [
        'section_label' => 'On Route',
        'items' => [
            [
                'label' => 'Route Navigation',
                'route' => 'driver.*',
                'route_url' => 'driver.dashboard',
                'letter' => 'R',
                'tooltip' => 'Route Navigation',
            ],
        ],
    ],
];
