name: Laravel Check
on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pcntl, posix, pdo_sqlite
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Install NPM Dependencies & Build
        run: |
          npm ci
          npm run build

      - name: Prepare Environment
        run: |
          cp .env.example .env
          php artisan key:generate --force

      - name: Run Tests
        run: php artisan test --parallel